.PHONY: clean All

All:
	@echo "----------Building project:[ OhaAlgorithmCodeLite - Debug ]----------"
	@cd "OhaAlgorithmCodeLite" && "$(MAKE)" -f  "OhaAlgorithmCodeLite.mk"
clean:
	@echo "----------Cleaning project:[ OhaAlgorithmCodeLite - Debug ]----------"
	@cd "OhaAlgorithmCodeLite" && "$(MAKE)" -f  "OhaAlgorithmCodeLite.mk" clean
